export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const PRODUCTS_FAILED = 'PRODUCTSS_FAILED';

export const PARTNERS_LOADING = 'PARTNERS_LOADING';
export const ADD_PARTNERS = 'ADD_PARTNERS';
export const PARTNERS_FAILED = 'PARTNERS_FAILED';